<?php

return [
    // Google Analytics Tracking code for the site.
    'ga_tracking_code' => 'UA-47482933-3',
    // Cache Sentora public API requests for X minutes!
    'sentora_api_cache_timeout' => 10,
    // Quicker way of manipulating teams and team members for the 'about/the-team' page.
    'team' => [
        ['name' => 'Project Owners',
            'members' => [
                ['name' => 'Tom Gates',
                    'role' => 'Support Lead',
                    'gravatar_email' => 'tgates@mach-hosting.com',
                    'social_facebook' => 'https://www.facebook.com/tom.djjoker',
                    'social_googleplus' => 'https://google.com/+TomGates71',
                    'social_github' => 'https://github.com/TGates71',
                ],
                [
                    'name' => 'Pascal Peyremorte',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => 'p.peyremorte@wanadoo.fr',
                    'social_github' => 'https://github.com/5050',
                ],
                [
                    'name' => 'Sam Mottley',
                    'role' => 'Developer',
                    'gravatar_email' => 'sammottleys@gmail.com',
                    'social_twitter' => 'https://twitter.com/sammottley',
                    'social_github' => 'https://github.com/motters',
                ],
            ],
        ],
        ['name' => 'Core Developement Team',
            'members' => [
                [
                    'name' => 'Kevin Andrews',
                    'role' => 'Developer',
                    'gravatar_email' => 'kevin@nforced.co.uk',
                    'social_twitter' => 'http://twitter.com/_zVPS',
                    'social_googleplus' => 'https://plus.google.com/109111406765342914674/',
                    'social_github' => 'https://github.com/Caffe1neAdd1ct',
                ],
                [
                    'name' => 'Sam Mottley',
                    'role' => 'Developer',
                    'gravatar_email' => 'sammottleys@gmail.com',
                    'social_twitter' => 'https://twitter.com/sammottley',
                    'social_github' => 'https://github.com/motters',
                ],
            ],
        ],
        ['name' => 'Development Support Team',
            'members' => [
                [
                    'name' => 'Pascal Peyremorte',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => 'p.peyremorte@wanadoo.fr',
                    'social_github' => 'https://github.com/5050',
                ],
                [
                    'name' => 'Jacob Gelling',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => 'jacobg830@icloud.com',
                    'social_twitter' => 'https://twitter.com/jacobg830',
                    'social_googleplus' => 'https://plus.google.com/102914300436620351748/',
                    'social_github' => 'https://github.com/jacobg830',
                ],
                [
                    'name' => 'Nigel Caldwell',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => 'zpanel.xystems@gmail.com',
                    'social_facebook' => 'https://www.facebook.com/pstwo.guy',
                    'social_twitter' => 'https://twitter.com/PS2Guy',
                    'social_googleplus' => 'https://plus.google.com/+NigelCaldwell',
                    'social_github' => 'https://github.com/PS2Guy',
                ],
                [
                    'name' => 'Lottfy Khalifa',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => '',
                    'social_facebook' => 'https://www.facebook.com/e7trs',
                ],
                [
                    'name' => 'Lee McKay',
                    'role' => 'Developer Support Analyst',
                    'gravatar_email' => 'leemk616@gmail.com',
                    'social_github' => 'https://plus.google.com/+LeeMcKay/',
                ],
            ],
        ],
        [
            'name' => 'Support Team',
            'members' => [
                ['name' => 'Tom Gates',
                    'role' => 'Support Lead',
                    'gravatar_email' => 'tgates@mach-hosting.com',
                    'social_facebook' => 'https://www.facebook.com/tom.djjoker',
                    'social_googleplus' => 'https://google.com/+TomGates71',
                    'social_github' => 'https://github.com/TGates71',
                ],
                [
                    'name' => 'Jay Laforteza',
                    'role' => 'Forum Support Analyst',
                    'gravatar_email' => '',
                    'social_facebook' => 'https://www.facebook.com/Yajster',
                    'social_twitter' => 'https://twitter.com/Yajster',
                    'social_googleplus' => 'https://plus.google.com/115882281616819131634/posts',
                    'social_github' => '',
                ],
                [
                    'name' => 'Pieter du Plooy',
                    'role' => 'Forum Support Analyst',
                    'gravatar_email' => '',
                    'social_facebook' => 'https://www.facebook.com/sentoracp',
                    'social_twitter' => '',
                    'social_googleplus' => '',
                    'social_github' => '',
                ],
                [
                    'name' => 'Mehdi',
                    'role' => 'Forum Support Analyst',
                    'gravatar_email' => '',
                    'social_facebook' => 'https://www.facebook.com/sentoracp',
                    'social_twitter' => '',
                    'social_googleplus' => '',
                    'social_github' => '',
                ],
                [
                    'name' => 'Remmy Adewale',
                    'role' => 'Forum Support Analyst',
                    'gravatar_email' => 'goremmy@gmail.com',
                    'social_facebook' => 'https://www.facebook.com/goremmy',
                    'social_twitter' => 'https://twitter.com/goremmy',
                    'social_github' => 'https://github.com/modpluz',
                ],
            ],
        ],
    ],
];
